
all:
    cd libarduinocore && $(MAKE)
    cd libarduinowire && $(MAKE)
    cd libarduinospi && $(MAKE)
    cd blink && $(MAKE)
    cd i2ceeprom && $(MAKE)

clean:
    cd libarduinocore && $(MAKE) clean
    cd libarduinowire && $(MAKE)
    cd libarduinospi && $(MAKE)
    cd blink && $(MAKE) clean
    cd i2ceeprom && $(MAKE) clean