
all:
    cd libarduinocore && $(MAKE)
    cd libwire && $(MAKE)
    cd blink && $(MAKE)
    cd i2ceeprom && $(MAKE)

clean:
    cd libarduinocore && $(MAKE) clean
    cd libwire && $(MAKE) clean
    cd blink && $(MAKE) clean
    cd i2ceeprom && $(MAKE) clean